### ISSUE TITLE
cannot see mapping speed

### ISSUE THREAD

**Issue by 2387882242** [LooseLab/readfish#78]
Hi,

I tested unblock-all using your bulk file and everything went well. 
Then I go ahead to test basecalling and mapping, the readfish validate result is success. But after I run the readfish targets command, I cannot see messages reporting the speed of mapping in the terminal window, as you can see in the screenshot below. So I don't know if mapping works properly. Of course, the readfish summary results are not what we expected.

My TOML file:
[caller_settings]
config_name = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/home/grid/software/minimap2/ref_human.mmi"

[conditions.0]
name = "select_2"
control = false
min_chunks = 0
max_chunks = inf
targets = ["NC_000001.11","NC_000002.12"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

![Screenshot from 2020-09-23 15-23-44](https://user-images.githubusercontent.com/71755194/93985475-b7a35a80-fdb7-11ea-867b-88582d7987f5.png)
![Screenshot from 2020-09-23 15-31-15](https://user-images.githubusercontent.com/71755194/93985505-c38f1c80-fdb7-11ea-8198-386a0a67540b.png)

I don't know what went wrong and I hope to get your help. I look forward to replying.

**Comment by alexomics** [comment]
How long did you run this simulation for? 

We would also recommend using a reference that doesn't use alt contigs as these as for this summary we only use the first alignment. In a reduced reference these reads would likely map elsewhere

**Comment by 2387882242** [comment]
Thank you very much for your reply.

I ran the simulation for about 90 minutes. By the way, may I ask you for a recommended test reference's link? So I can avoid these errors, including the target name error and so on to get the same result as yours. Thank you!

**Comment by alexomics** [comment]
We use the latest assembly that we can, in this case I'd use the [GRCh38_no_alt_analysis_set](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.28_GRCh38.p13/GRCh38_major_release_seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz) and remove any contigs where the role is `unplaced`, `unlocalized`, or `decoy`; this should just leave `Mitochondrion` and `Chromosome` contigs.

**Comment by 2387882242** [comment]
Thank you very much for your kind reply. I will try it now.

**Comment by mattloose** [comment]
Can you confirm which software versions you are using? I suspect there are other issues here as well.

**Comment by 2387882242** [comment]
The version of readfish I used was 0.0.5a1.
Guppy：4.0.15
Minknow GUI：4.0.20
Ubuntu 16 

I haven't been able to install readfish0.0.5a2 successfully yet, probably due to a python version problem, but Unblock-all works fine. Is it the impact of this？

**Comment by 2387882242** [comment]
Hi mattloose，

As you said, there are other problems. 
I used the reference given by Alex, but the speed of mapping displayed in terminal is 3R/238.51618/s. What a big number! 
The readFish Summary results are also not as expected. So how do I check what's wrong?

Looking forward to your reply！Thank you very much!

**Comment by mattloose** [comment]
So - there's a number of things here....
You should try installing readfish 0.0.5a2.
On your readfish command set the following:
--action-throttle 0.4 --throttle 0.4

Switch from the HAC model to the FAST model.

Let us know your timings.

There is another fix we're working on as well which we will post as soon as we are confident about it.

**Comment by 2387882242** [comment]
Hi Matt，

Thank you for your advice, I did as you said, except I cannot installed readfish 0.0.5a2. 
I installed it by https://pypi.org/project/readfish/0.0.5a2/, and my python version is 3.7, but I can only install readfish 0.0.5a1 as shown blow. Should I uninstall readfish 0.0.5a1 and reinstall?
![图片](https://user-images.githubusercontent.com/71755194/97885557-7ca32800-1d62-11eb-9678-aebf665c71cc.png)

Apart from this, the mapping speed seems normal now. 
But when I ran readfish for 15 minutes, the  readfish summary results didn't seem so satisfactory. I noticed that ch1 and ch2 had fewer numbers than the rest, but the mean read lengths was not significantly longer as shown blow.
![图片](https://user-images.githubusercontent.com/71755194/97885789-cab82b80-1d62-11eb-9cf2-0af2dc63dabc.png)

So is this playback result good enough for me to do a real experiment, or do I need to make other adjustments?
And is there any other way to tell how readfish is running apart from readfish summary?

My TOML file:
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/home/grid/software/minimap2/ref_human.mmi"

[conditions.0]
name = "select_2"
control = false
min_chunks = 0
max_chunks = 64
targets =  ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

I use it on GridION.
Guppy：4.0.15
Minknow GUI：4.0.20
Ubuntu 16

Looking forward for your reply! Thank you very much!

**Comment by mattloose** [comment]
Hi Sophie,

We just pushed a big update to our development branch. You should try this. I would make a complete fresh environment and see if this performs better. 

I'll ask @alexomics to confirm the minimum python version.

Cheers

Matt

**Comment by 2387882242** [comment]
Hi Matt，

Thank you for your reply, I'm sorry to bother you again. 

Is the branch you mentioned dev_documentation? 
I tried it, and now my readfish version is 0.0.5a4, and the Guppy version is 4.0.15. 
The unblock test was successful, but the mapping speed was still not so satisfactory. As shown in the following image, the speed of mapping seems to be increasing gradually.
![image](https://user-images.githubusercontent.com/71755194/98370974-605efe00-2076-11eb-9aab-800c62b724a8.png)

I want to know what went wrong and hope to get your help！

**Comment by mattloose** [comment]
Hi
Glad the unblock all scipt worked.

The branch you should be using is the "dev" branch - not the dev_documentation branch.

Can you remind me which toml you are using AND are you definitely using GPU basecalling?

There are some additional speed up instructions you can use available on the wiki here:

https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

Hope this helps you!

Best wishes,

Matt

**Comment by 2387882242** [comment]
Hi Matt,

My TOML file is :
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "127.0.0.1"
port = 5555

[conditions]
reference = "/home/grid/software/minimap2/ref_human.mmi"

[conditions.0]
name = "select_2"
control = false
min_chunks = 0
max_chunks = 64
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"

I use it on GridION X5.
Readfish：0.0.5a4
Guppy：4.0.15
Minknow GUI：4.0.20
Ubuntu 16.

I'm using the GPU that come with GridIon X5 to basecalling, but it doesn't seem to work very well. Maybe something went wrong.
How do I know if I'm using GPU for basecalling?And how do I set up basecalling with GPU?

Thank you very much!

**Comment by mattloose** [comment]
Hi Sophie,

Try having a read here:

https://github.com/LooseLab/readfish/wiki/Basecalling-Settings

Also - are you on gridION mk1 or an original gridion?

CHeers

Matt

**Comment by 2387882242** [comment]
Hi Matt,

Thank you for your reply. I've browsed the wiki. I set my test the same toml, but the result is not as good as yours.
I am on gridion X5, it should be original gridion. What's up with that?

Sophie

**Comment by mattloose** [comment]
Original GridION has different GPU to the current Mk1 - on that basis I would expect it to be not quite as good as what we see.

To be explicit - have you tried editing the basecalling config as described in the wiki to comment out the as_model_file line?

We do know that read until works on the original gridION - I think commenting out that as_model_file line in the fast model SHOULD work.
